name: wtracker
description: A weight tracking app.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0+4
  sqlite3: ^1.5.1
  sqlcipher_flutter_libs: ^0.6.0
  path: ^1.8.3
  intl: ^0.18.0
  path_provider: ^2.1.1
  fl_chart: ^0.68.0
  file_picker: ^5.3.3
  shared_preferences: ^2.2.2
  provider: ^6.0.0
  flutter_local_notifications: ^15.1.1
  flutter_secure_storage: ^8.0.0
  permission_handler: ^11.0.0
  android_intent: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true